### PR TITLE
Make push/pop avoid killing the queue's GenServer after default 5000ms timeout

### PR DESCRIPTION
**Pull request by cboggs**

### CODE REVIEW

**Comment by cboggs** [comment]
One drawback of the tests I wrote is that they jump the total test runtime to ~12 seconds. Not sure how best to get around that, though, while still testing that pushing/poping processes don't die after 5s.

**Comment by joekain** [comment]
HI @cboggs,

Thanks a lot for the pull request!  

Yeah, the tests taking 12 seconds is kind of a big deal.

I was thinking about this yesterday after you asked about the timeouts and I wonder if something like this might be a better approach:

1. Instead of sending :noreply when the caller needs to block send back a reply that says :block.
2. In the client code when it's time to block do a receive to wait for a message.  Maybe called :awaken.  This receive can have a timeout of :infinity.
3. When data becomes available and there is a waiter send it the new :awaken message with the data.

This is more involved but I think that one advantage here is that it doesn't impact the GenServer timeout.  I think we probably want to keep the GenServer timeout functionality in the case that BlockingQueue gets stuck for some other reason.

If you were to try this out and it works then I think you could test by setting the GenServer timeout to some very low value, 2m for example.  And we wouldn't trigger that timeout even if the queue blocks for more than 2ms.  That will keep the tests fasts.

Does that seems like it would work?

**Comment by cboggs** [comment]
Yea, I figured the test timing would be a bit of a deal-breaker. :-)

I like your idea about making it a receive timeout instead of messing with the GenServer timeout - this PR is, admittedly, a sledgehammer fix.

I _think_ I understand what would be needed to make your idea work, but not positive. I'll think on it some more and see if I can make it work - unless you beat me to it, which I'd be just fine with too!

**Comment by joekain** [comment]
Thanks @cboggs, I don't think I'll have time to work on this directly this week.  But am happy to review and PRs or answer any questions.

**Comment by cboggs** [comment]
Finally coming back to this, just a quick clarification if you have a minute...

Are you thinking that users of BlockingQueue's should just take into consideration how to handle such messaging on their own?

Or were you thinking more along the lines of "provide a bit of client code that wraps up this handling for the user"?

I'm not entirely sure how best to go about the latter in a generic way. I can imagine ways to handle this ad-hoc, but not sure how to wrap it up nice and neat.

**Comment by joekain** [comment]
Hi @cboggs,

My thinking was the later.  And to put a lot most of the work into the client side functions `push/2` and `pop/2`.  These functions don't do much now but could.  Both are synchronous calls so they can do things in responds to the reply from the server.  My thinking was that they would send the request and the examine the result.  Take push for example, it could receive one of two results:

* :ok - if the push was done
* :wait - if the push could not be done.  If it receives this it needs to call receive to wait for another message that will come when the push actually happens (i.e. when the waiter is processed in the server)

So certainly the client side functions will become a little more involved.  I think that's ok.  I think it makes some sense to push some of the work into the client.  That lightens the responsibility of the server which can be a good thing.

Thoughts?

**Comment by cboggs** [comment]
I goofed up my fork in a really bad way, so my branch is blown away at this point. Going to close this PR and open a new one with my latest attempt.

**Pull request closed without merging**
